# Generated by Django 4.2.11 on 2024-07-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=150)),
                ('max_seat', models.IntegerField()),
                ('date', models.DateField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('web_site', models.URLField(blank=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.company')),
            ],
        ),
    ]
