# Generated by Django 4.2.11 on 2024-07-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.company'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
