# Generated by Django 4.2.11 on 2024-07-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_company_email_alter_event_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='media/noImage.png', null=True, upload_to=''),
        ),
    ]
