# Generated by Django 4.2.11 on 2024-07-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='noImage.png', null=True, upload_to=''),
        ),
    ]
