# Generated by Django 4.2.11 on 2024-07-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('seat_number', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.event')),
            ],
        ),
    ]
