# Generated by Django 4.2.11 on 2024-07-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('free', '自由席'), ('reserved', '指定席')], max_length=10),
        ),
    ]
