# Generated by Django 4.2.11 on 2024-08-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_ticket_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('people_num', models.IntegerField()),
                ('payment', models.CharField(choices=[('bank', '銀行振込'), ('credit', 'クレジットカード決済')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.ticket')),
            ],
        ),
    ]
